# Generated by Django 4.2.7 on 2024-11-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarregistrationmodel',
            name='payment_plan',
            field=models.CharField(choices=[(6000, 'Half-Payment (₦6,000)'), (12000, 'Full-Payment (₦12,000)')], default=6000, max_length=255),
        ),
    ]
