# Generated by Django 4.2.7 on 2024-11-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0003_alter_scholarregistrationmodel_payment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarregistrationmodel',
            name='email_address',
            field=models.EmailField(error_messages={'unique': 'This email has been registered already.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='scholarregistrationmodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Rather not say', 'Rather not say')], max_length=255),
        ),
        migrations.AlterField(
            model_name='scholarregistrationmodel',
            name='payment_plan',
            field=models.IntegerField(choices=[(6000, 'Half-Payment (₦6,000)'), (12000, 'Full-Payment (₦12,000)')]),
        ),
    ]
