# Generated by Django 4.2.7 on 2024-11-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0005_alter_scholarregistrationmodel_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarregistrationmodel',
            name='about',
            field=models.TextField(error_messages={'max_length': 'Your about should not be more than 5000 words'}, max_length=5000),
        ),
        migrations.AlterField(
            model_name='scholarregistrationmodel',
            name='email_address',
            field=models.EmailField(error_messages={'unique': 'The email you provided has been registered already.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='scholarregistrationmodel',
            name='expectations',
            field=models.TextField(error_messages={'max_length': 'Your expectation should not be more than 5000 words'}, max_length=5000),
        ),
    ]
